### ISSUE TITLE
Parse *all* of JSON, not just arrays and objects

### ISSUE THREAD

**Issue by passcod** [flori/json#131]
Quoting Crockford:

> JSON can represent four primitive types (strings, numbers, booleans,
> and null) and two structured types (objects and arrays).

This really means that all of these (one line each) are valid JSON documents:

```
"string"
12345
12.345
true
false
{}
[]
```

Currently, this gem only parses and generates the last two. Adding support for the rest should not be too big a thing. Currently this can be worked around by putting `[` and `]` around the value to be parsed or generated, and remove them afterward, but this is in no way elegant :(

**Comment by Ajedi32** [comment]
Quick note for others like me who might be running into this problem. Despite this issue being resolved as "wontfix", the latest version of this gem does indeed accept all valid JSON values. TL;DR: Update the gem and it'll work.

Back when this issue was first posted, I believe [RFC4627](https://www.ietf.org/rfc/rfc4627.txt) was the standard it was following. This is the standard @flori was referencing in previous comments. Today though, RFC4627 is not the prevailing standard for JSON, and the document explicitly says at the top:

> This memo provides information for the Internet community. **It does not specify an Internet standard of any kind.**

(Emphasis mine.)

Today there are actually two competing standards for JSON, [ECMA-404](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) and [RFC7159](https://tools.ietf.org/html/rfc7159).

ECMA-404 states:

> A JSON text is a sequence of tokens formed from Unicode code points that conforms to the JSON value grammar.
>
> [...]
>
> A JSON value can be an object, array, number, string, true, false, or null. 

So we go by the ECMA-404 standard, all values are indeed valid JSON documents.

The other competing JSON standard is [RFC7159](https://tools.ietf.org/html/rfc7159#section-2), which is the one this gem is currently following. That RFC states:

> A JSON text is a sequence of tokens. The set of tokens includes six structural characters, strings, numbers, and three literal names. **A JSON text is a serialized value.**

So RFC7159 is in agreement with ECMA-404 here.

The text goes on to say:

> Note that certain previous specifications of JSON constrained a JSON text to be an object or an array. Implementations that generate only objects or arrays where a JSON text is called for will be interoperable in the sense that all implementations will accept these as conforming JSON texts.

So older versions of this gem are still considered interoperable, but they don't conform to the latest standards.
