### ISSUE TITLE
JSON load nil raises error

### ISSUE THREAD

**Issue by rhymes** [flori/json#289]
I tried to upgrade to json and json_pure 2.0.1 but I get the error mentioned here:

json 1.8.3

> [1] pry(main)> JSON.load(nil)
> => nil
> 

json 2.0.1

[4] pry(main)> JSON.load(nil, nil, allow_blank: true)
JSON::ParserError: 784: unexpected token at 'null'
from /Users/rhymes/.rvm/gems/ruby-2.3.1/gems/json_pure-2.0.1/lib/json/common.rb:156:in `parse'

**Comment by flori** [comment]
Can you `require 'json_pure'` explicitly and then call `JSON.load(nil)`? Also what does `JSON.parser` return?

**Comment by mitnal** [comment]
Had the same problem and `require 'json/pure'` fixed it.

```
[1] pry(main)> JSON.load(nil)
JSON::ParserError: 757: unexpected token at 'null'
from .../gems/json_pure-2.0.1/lib/json/common.rb:156:in `parse'
[2] pry(main)> JSON.parser
=> JSON::Ext::Parser
[3] pry(main)> require 'json/pure'
=> true
[4] pry(main)> JSON.load(nil)
=> nil
[5] pry(main)> JSON.parser
=> JSON::Pure::Parser
```

**Comment by flori** [comment]
The problem seems to be that the loading of the < 2.0 json and the >= 2.0 version seems to be mixed up in your cases. The 2.0 load method doesn't pass an argument that's necessary for 1.8 but not supported by the 2.0 parsers. But it's a bit concerning that the loading can be mixed up like that at all.

**Comment by mitnal** [comment]
@flori I looked a litte bit closer at my Gemfile.lock (see below) and you are right. I am loading `json 1.8.3` (active support) and `json_pure 2.0.1` (aws-sdk-core -> jmespath). We do not specify json or json_pure directly inside our Gemfile. 

If I specify `gem 'json_pure', '< 2'` inside my Gemfile everything is working because I am using version 1.8.3 of both gems.

Gemfile.lock snippet (some json mentions):
```
activesupport (4.2.6)
  i18n (~> 0.7)
  json (~> 1.7, >= 1.7.7)
  minitest (~> 5.1)
  thread_safe (~> 0.3, >= 0.3.4)
  tzinfo (~> 1.1)
fog-json (1.0.2)
  fog-core (~> 1.0)
  multi_json (~> 1.10)
newrelic_plugin (1.3.1)
  json
grape (0.8.0)
  activesupport
  builder
  hashie (>= 2.1.0)
  multi_json (>= 1.3.2)
  multi_xml (>= 0.5.2)
  rack (>= 1.3.0)
  rack-accept
  rack-mount
  virtus (>= 1.0.0)
jbuilder (2.5.0)
  activesupport (>= 3.0.0, < 5.1)
  multi_json (~> 1.2)
aws-sdk-core (2.3.19)
  jmespath (~> 1.0)
jmespath (1.2.4)
  json_pure (>= 1.8.1)
simplecov (0.12.0)
  docile (~> 1.1.0)
  json (>= 1.8, < 3)
  simplecov-html (~> 0.10.0)
json (1.8.3)
json_pure (2.0.1)
multi_json (1.12.1)
```

**Comment by flori** [comment]
I am still not sure what to do about it.

**Comment by mitnal** [comment]
@flori I do no longer have this problem because jmespath removed their hard dependency on `json_pure` in 1.3.1.

See: 
https://github.com/jmespath/jmespath.rb/releases/tag/v1.3.1
https://github.com/jmespath/jmespath.rb/pull/36/commits/e3ebb185870365216749bf4b2b7f7df6a0b0c2b8
